#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# A prt-utils/prg-get/ports/pkgmk/pkgadd wrapper

if [[ "$#" -ge 1 ]]; then
	case "$1" in
		-h|--help)
			echo "-c         clean"
			echo "-i pkg     info"
			echo "-s pkg     search"
			echo "-S pkg     search local"
			echo "-f pkg     search files"
			echo " + pkg     install"
			echo " - pkg     uninstall"
			echo "           update"
			;;
		-c)
			all="$(prt-get listorphans)"
			keep="$(cat $HOME/.keepers)"
			orphan="$(echo -e "$all\n$keep" | sort | uniq -u)"
			count="$(echo "$orphan" | wc -l)"

			# TODO: displays () when there are no orphans
			# TODO: Make this look like +
			if [[ "$count" -eq 1 ]]; then
					read -p "$count orphaned package found ($orphan), do you want to remove it? [y/N] " answer
					case "$answer" in
						[Yy]*)
							sudo prt-get cache
							pkgfoster
							;;
						*)
							;;
					esac
			# TODO: Fix \n here
			elif [[ "$count" -ge 2 ]]; then
					read -p "$count orphaned packages found ($orphan), do you want to remove them? [y/N] " answer
					case "$answer" in
						[Yy]*)
							sudo prt-get cache
							pkgfoster
							;;
						*)
							;;
					esac
			else
				echo "No orphaned packages found."
			fi
			shift
			;;
		-i)
			shift
			if [[ "$#" -ge 1 ]]; then
				results="$(prt-get info "$@" 2> "/dev/null")"

				if [[ "$results" =~ ^Package ]]; then
					echo "$results"
				else
					echo "No matching package(s) found."
				fi
			else
				echo "No search term(s) provided."
			fi
			shift
			;;
		-s)
			# TODO: error "prt-get dsearch takes exactly 1 argument"
			shift
			if [[ "$#" -ge 1 ]]; then
				results="$(prt-get dsearch "$@" -vv | tr ":" "\n")"

				if ! [[ "$results" =~ ^No ]]; then
					echo "$results"
				else
					echo "No matching package(s) found."
				fi
			else
				echo "No search term(s) provided."
			fi
			shift
			;;
		-S)
			# TODO: error "prt-get dsearch takes exactly 1 argument"
			shift
			if [[ "$#" -ge 1 ]]; then
				results="$(prt-get listinst "$@" -vv)"

				if ! [[ -z "$results" ]]; then
					echo "$results"
				else
					echo "No matching package(s) found."
				fi
			else
				echo "No search term(s) provided."
			fi
			shift
			;;
		-f)
			shift
			if [[ "$#" -ge 1 ]]; then
				results="$(prt-get fsearch "$@")"

				if ! [[ -z "$results" ]]; then
					echo "$results"
				else
					echo "No matching package(s) found."
				fi
			else
				echo "No search term(s) provided."
			fi
			shift
			;;
		+)
			shift
			if [[ "$#" -ge 1 ]]; then
				for package in "$@"; do
					# TODO: Maybe remove sort here?
					# +ing a non existing package glitches out
					deps="$(prt-get depends "$package" | grep -v "] $package$" | grep "\[ \]" | cut -d " " -f 3- | sort | nl)"

					if [[ -n "$deps" ]]; then
						echo "Installing $package, the following dependencies will also be installed:"
						echo "${deps}"
						read -p "Do you want to continue? [y/N] " answer
						case "$answer" in
							[Yy]*)
								# TODO: Remove prt-get: updating line
								if [[ -z "$(prt-get listinst | grep "$package")" ]]; then
									sudo prt-get depinst "$package"

									if [[ "$?" -eq 0 && -n "$DISPLAY" ]]; then
										notify "Installation finished: $@" & disown
									elif [[ "$?" -ge 1 && -n "$DISPLAY" ]]; then
										notify "Installation failed: $@" & disown
									fi
								else
									sudo prt-get update "$package"

									if [[ "$?" -eq 0 && -n "$DISPLAY" ]]; then
										notify "Installation finished: $@" & disown
									elif [[ "$?" -ge 1 && -n "$DISPLAY" ]]; then
										notify "Installation failed: $@" & disown
									fi
								fi
								;;
							*)
								;;
						esac
					else
						if [[ -z "$(prt-get listinst | grep "$package")" ]]; then
							word=Installing
						else
							word=Updating
						fi

						read -p "$word $package, do you want to continue? [Y/n] " answer
						case "$answer" in
							[Nn]*)
								;;
							*)
								# TODO: Remove prt-get: updating line
								if [[ -z "$(prt-get listinst | grep "$package")" ]]; then
									sudo prt-get depinst "$package"

									if [[ "$?" -eq 0 && -n "$DISPLAY" ]]; then
										notify "Installation finished: $@" & disown
									elif [[ "$?" -ge 1 && -n "$DISPLAY" ]]; then
										notify "Installation failed: $@" & disown
									fi
								else
									sudo prt-get update "$package"

									if [[ "$?" -eq 0 && -n "$DISPLAY" ]]; then
										notify "Installation finished: $@" & disown
									elif [[ "$?" -ge 1 && -n "$DISPLAY" ]]; then
										notify "Installation failed: $@" & disown
									fi
								fi
								;;
						esac
					fi
				done
			else
				echo "No package(s) provided."
			fi
			shift
			;;
		-)
			shift
			if [[ "$#" -ge 1 ]]; then
				# TODO: Also remove deps here
				# TODO: Add custom pkg not found error here?
				sudo prt-get remove "$@"
				if [[ "$?" -eq 0 && -n "$DISPLAY" ]]; then
					bash "$SCRIPTS/apps/notify.sh" "Uninstallation finished: $@" & disown
				fi
			else
				echo "No package(s) provided."
			fi
			;;
		*)
			echo "Invalid option, use -h for help."
			;;
	esac
else
	sudo ports -u
	update="$(prt-get quickdiff)"

	echo "The following packages will be updated:"

#	read -p "Do you want to continue? [Y/n] " answer
#	case
#		[Nn]*)
#			;;
#		*)
#			;;
#	esac
fi
