#!/bin/bash
#
# allmk - Recompile all installed packages
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Config location
config="/etc/mk.conf"

# Upgraded packages list location
upgraded="/home/onodera/upgraded"


## EXECUTE

ports="$(ports -l)"
installed="$(pkginfo -i | cut -d " " -f 1)"
order="$(grep "^order" "$config" | cut -d " " -f 2-)"

for package in $installed; do
	location="$(echo "$ports" | grep "/$package$")"

	# Recompile
	if [[ -n "$(grep "$location" "$upgraded")" ]]; then
		continue
	fi

	# Order
	if [[ "$(echo "$location" | wc -l)" -ge 2 ]]; then
		for line in $order; do
			location="$(echo "$location" | grep "^$line/")"
			if [[ "$?" -eq 0 ]]; then
				break
			fi
		done
	fi

	cd "/usr/ports/$location"

	echo "=======> RECOMPILING: $location"
	read -p "Do you want to recompile this package? [Y/n] " answer
	case "$answer" in
		[Nn]*)
			echo "$location" >> "$upgraded"
			continue
			;;
		*)
			sudo pkgmk -d -u -f
			if [[ "$?" -ge 1 ]]; then
				exit 1
			else
				echo "$location" >> "$upgraded"
			fi
			;;
	esac
done
