#!/bin/bash
#
# cdm - cd to current playing album dir
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Set music dir location
musicdir="$HOME/media/music"


## EXECUTE

location="$(mpc -f "%file%" | head -n 1 | cut -d "/" -f -2)"
cd "$musicdir/$location"

