#!/bin/bash
#
# cdp - cd to port
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Config location
config="/etc/mk.conf"


## EXECUTE

if [[ "$#" -ge 1 ]]; then
	order="$(grep "^order" "$config" | cut -d " " -f 2-)"

	location="$(ports -l | grep "/$@$")"

	# Order
	# TODO: Find a better way of doing this?
	# TODO: Doesn't work with source
	if [[ "$(echo "$location" | wc -l)" -ge 2 ]]; then
		for line in $order; do
			echo a
			locationorder="$(echo "$location" | grep "^$line/")"
			if [[ -n "$locationorder" ]]; then
				location="$locationorder"
				echo "$location"
				break
			fi
		done
	fi

	if [[ -d "/usr/ports/$location" ]] && [[ -n "$location" ]]; then
		cd "/usr/ports/$location"
	else
		echo "cdp: invalid port $1"
		cd "/usr/ports"
	fi
else
	cd "/usr/ports"
fi
