#!/bin/bash
#
# cover -  A small script to easily resize and view album art
# onodera, https://github.com/onodera-punpun

# TODO: -a doesn't resize covers with unicode in the path (or something)

## CONFIGURATION

# Set music dir locations
musicdir="$HOME/media/music"

# Set cover size
size=160x160

fg="\e[0;39m"
c1="\e[1;33m"


## EXECUTE

if [[ "$#" -ge 1 ]]; then
	case "$1" in
		-h|--help)
			echo "-a         resize all covers"
			echo "-c         resize current playing album cover"
			echo "           show current playing album cover "
			;;
		-a)
			path="$(find "$musicdir" -name "cover.*" | sort)"

			all="$(echo "$path" | wc -l)"
			number=0

			read -p "Do you want to resize $all covers to $size? [y/N] " answer
			case "$answer" in
				[Yy]*)
					IFS=$'\n'
					for line in $path; do
						number="$((number + 1))"
						album="$(echo "$line" | cut -d "/" -f 7 | cut -d " " -f 3-)"
						output="$(echo "$line" | cut -d "." -f -1)"

						echo -e "Resizing cover $number/$all, $c1$album$fg."
						convert "$line" -resize $size! "${output}_popup.png" 2> "/dev/null"
						if [[ "$?" -ge 1 ]]; then
							exit
						fi
					done
					;;
				*)
					exit
					;;
			esac
			;;
		-c)
			path="$(mpc -f "%file%" | cut -d $'\n' -f 1 | cut -f 1-2 -d "/")"

			convert "$musicdir/$path/cover."* -resize $size! "$musicdir/$path/cover_popup.png" 2> "/dev/null"

			if [[ "$?" -eq 0 ]]; then
				echo "Cover resized successfully."
			else
				echo "This album doesn't have a cover."
			fi
			;;
		*)
			echo "Invalid option, use -h for help."
			;;
	esac
else
	path="$(mpc -f "%file%" | cut -d $'\n' -f 1 | cut -f 1-2 -d "/")"

	img  "$musicdir/$path/cover."* 2> "/dev/null"

	if [[ "$?" -ge 1 ]]; then
		echo "This album doesn't have a cover."
	fi
fi
