#!/bin/fish
#
# fishbuzz - fizzbuzz
# onodera, https://github.com/onodera-punpun

## EXECUTE

for i in (seq 100)
	set -e p

	if test (math $i \% 3) -eq 0
		set p true
		echo -n fish
	end
	if test (math $i \% 5) -eq 0
		set p true
		echo -n buzz
	end
	if test -z $p
		echo -n $i
	end

	echo
end
