#!/bin/fish
#
# fuzzy - Kind of fuzzy logic search thingy.
# onodera, https://github.com/onodera-punpun

for thing in $argv[-1]
	set match 0

	for word in $argv[1..-2]
		set wordmatch (string match -r -i -a -n $word $argv | string replace -r '.* ' '')
		if test $status -ge 1
			continue
		end
		set wordmatch (string join ' + ' $wordmatch)

		set match (math $match + $wordmatch)
	end

	echo $match $directory
end
