#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Display current playing song

foreground="\e[0;39m"
brown="\e[1;33m"
green="\e[1;32m"
magenta="\e[1;35m"

album="$(mpc -f "%album%" | head -n 1)"
artist="$(mpc -f "%artist%" | head -n 1)"
title="$(mpc -f "%title%" | head -n 1)"

echo -e "Currently playing $green$title$foreground by $magenta$artist$foreground on $brown$album$foreground"
