#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Change mpd output in a pretty way

foreground="\e[0;39m"
brown="\e[1;33m"

output="$(mpc outputs | grep -o "(.*)" | grep -o "[a-z]*")"
current="$(mpc outputs | grep "enabled" | grep -o "(.*)" | grep -o "[a-z]*")"
count="$(echo "$output" | wc -l)"

echo -e "There are $count mpd outputs, the current output is $brown$current$foreground:"
echo ""
echo "$(echo "$output" | nl | sed "s/^ */  /g")"
echo ""
read -p "Which output do you want to enable [1-$count] " answer
case "$answer" in
	[1-$count])
		mpc  enable only $answer 1> "/dev/null"
		echo -e "Enabled the output $brown$(echo "$output" | cut -d $'\n' -f $answer)$foreground."
		;;
	*)
		echo "$answer is not a valid mpd output."
		;;
esac

