#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# A script to easily play and manage your escapism

# TODO: add read -p if there are fuzzies with the same matches
# TODO: Move config to etc and add rc
# TODO: Disable config.bak

foreground="\e[0;39m"
brown="\e[1;33m"

info() {
	show="$(cat "$HOME/bin/config/neet")"

	active="$(echo "$show" | grep "+")"

	name="$(echo "$active" | cut -d "|" -f 2- | cut -c 2- | tr -d "\r")"
	if [[ -z "$current" ]]; then
		current="$(echo "$active" | cut -d "/" -f 1 | cut -d "[" -f 2-)"
	fi
	total="$(echo "$active" | cut -d "]" -f 1 | cut -d "/" -f 2-)"

	genre="$(echo "$show" | grep -B 32 "+" | grep "#" | tail -n 1 | cut -c 3- | head -c -2)"
}

fuzzy() {
	directories="$(ls -d "$HOME/downloads/"*/ | cut -d "/" -f 5- | cut -d "/" -f -1)"


	mostlikely="$(
		IFS=$'\n'
		for directory in $directories; do
			unset IFS
			for word in $name; do
				echo "$directory" | grep -i "$(echo "$word" | tr -d ",")"
			done
		done
	)"

	count="$(echo "$mostlikely" | wc -l)"
	if [[ "$count" -ge 2 ]]; then
		echo -e "There are $count directories that match $brown$name$foreground:\n" 
		# TODO: Add grep color here like in aiko
		echo -e "$(echo "$mostlikely" | nl | sed "s/^ */  /g")\n"
		# TODO: This gets askes every time, save it?
		read -p "Which directory would you like to use? [1-$count] " answer
		case "$answer" in
			[1-$count])
				mostlikely="$(echo "$mostlikely" | cut -d $'\n' -f $answer)"
				echo ""
				;;
			*)
				exit
				;;
		esac
	elif [[ "$count" -eq 0 ]]; then
		echo "No match found."
		exit
	fi

	path="$(echo "$mostlikely" | uniq -c | sort | tail -n 1 | cut -d " " -f 8-)"

	# TODO: $currentmpv isn't alway needed, for example in "Padam Padam - 1.avi", but mostly it IS needed
	if [[ "$current" -eq 0 ]]; then
		currentmpv=01
	elif [[ "$current" -le 9 ]]; then
		for number in {1..9}; do
			if [[ "$number" -eq "$((10#$current))" ]]; then
				currentmpv=0$number
			fi
		done
	else
		currentmpv="$current"
	fi

	echo -e "Playing episode $current/$total, $brown$name$foreground."
#	mpc -q pause
	mpv --fullscreen "$HOME/downloads/$path/"*{E,Ep,\ }$currentmpv*{.avi,.mkv,.mp4}
}

if [[ "$#" -ge 1 ]]; then
	case "$1" in
		-h|--help)
			# TODO: Add change active escapism option
			echo "-e         edit list"
			echo "-s         sort list"
			echo "+          increment ep"
			echo "-          decrement ep"
			echo "           play"
			;;
		-e)
			$EDITOR "$HOME/bin/config/neet"
			;;
		-s)
			info

			count="$(grep -c "#" "$HOME/bin/config/neet")"

			for number in $(eval echo "{1..$count}"); do
				# TODO: Finish this
				echo -e "Sorted $brown$(grep -m $number "#" "$HOME/bin/config/neet" | tail -n 1 | cut -d " " -f 11- | tr -d "\r" | tr -d "\n")$foreground list."
			done

			echo -e "$active\n\n$sort1\n$sort2" > ~/test
			;;
		+)
			info

			shift
			if [[ "$current" -lt "$total" ]]; then
				increment="$((current + 1))"

				sed -i "s/+ \[$current\/$total\]/+ \[$increment\/$total\]/" "$HOME/bin/config/neet"
				current="$increment"

				# bash "$HOME/.bar/neet/neet_button.sh" & disown

				fuzzy
			else
				echo -n -e "$brown$name$foreground completed! Would you like to remove this $genre? [y/N] "
				read -p "" answer
				case "$answer" in
					[Yy]*)
						sed -i "/$name/d" "$HOME/bin/config/neet"
						;;
					*)
						exit
						;;
				esac
			fi
			shift
			;;
		-)
			info

			shift
			if [[ "$current" -ge 1 ]]; then
				decrement="$((current - 1))"

				sed -i "s/+ \[$current\/$total\]/+ \[$decrement\/$total\]/" "$HOME/bin/config/neet"
				current="$decrement"

				# bash "$HOME/.bar/neet/neet_button.sh" & disown

				fuzzy
			else
				echo "Can't go lower than 1!"
			fi
			shift
			;;
		*)
			echo "Invalid option, use -h for help."
			;;
	esac
else
	info
	fuzzy
fi
