#!/bin/fish
#
# notify - Display notifications using bar
# onodera, https://github.com/onodera-punpun

# TODO: Fix fullscreen windows fucking up when a notify comes along

## CONFIGURATION

# Set colors
set fg 021B21
set bg EEEEEE

# Set font
set font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1,-freetype-kochismall-medium-r-normal--9-90-75-75-p-77-iso10646-1,-freetype-baekmuksmall-medium-r-normal--9-90-75-75-p-38-iso10646-1


## EXECUTE

if test (count $argv) -ge 1
	switch $argv[1]
		case -h --help
			echo -e "Usage: notify [options] [message]\n"
			echo "options:"
			echo "  -h,   --help                print help and exit"
			exit 0
		case "*"
			# Kill old notification
			pkill -f "lemonbar -g 800x56"

			# Display notification
			echo "%{B#$bg}%{r}     $argv     " | lemonbar -g 800x56+1088+32 -p -f $font -B \#00$bg -F \#$fg &

			# Kill notification
			sleep 4
			set pid (jobs -p | cut -d \n -f 2)
			kill $pid ^ /dev/null
		end
else
	echo "Please specify a message."
	exit 1
end
