#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Display notifycations using bar

background="$(grep "^Colorset 1" "$HOME/etc/fvwm/config" | tail -c 9 | head -c 6)"
foreground="$(grep "^*foreground" "$HOME/etc/Xresources" | tail -c 7)"

font=-gohu-gohufont-medium-r-normal--14-100-100-100-c-80-iso10646-1,-misc-fixed-medium-r-normal-ja-13-120-75-75-c-120-iso10646-1

(echo "%{c}$@" ; sleep 4) |
lemonbar -g 800x40+560+1120 -d -f $font -B \#FF$background -F \#FF$foreground &
