#!/bin/bash
#
# notify - Display notifications using bar
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Set colors
bg="$(grep "bg" "$HOME/.fvwm/config" | tail -c 7)"
fg="$(grep "fg" "$HOME/.fvwm/config" | tail -c 9 | head -c -3)"

# Set font
font=-artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1


## EXECUTE

if [[ "$#" -ge 1 ]]; then
	case "$@" in
		-h|--help)
			echo "usage: notify [message]"
			echo "options:"
			echo "  -v,   --version             print version and exit"
			echo "  -h,   --help                print help and exit"
			exit 0
			;;
		-v|--version)
			echo "notify 0.4"
			exit 0
			;;
		*)
			# Calculate width & position of bar
			width="$(($(echo "      $@      " | wc -m) * 5))"
			left="$((1859 - width))"

			# Kill old notifycation
			pkill -f -n "FFEEEEE"

			# Display notifcation
			(echo "%{c}$@" ; sleep 4) |
			lemonbar -g ${width}x56+$left+1090 -d -f $font -B \#FF$bg -F \#FF$fg & disown
			;;
	esac
else
	echo "Please specify a message."
	exit 1
fi


