#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Displays installed packages

foreground="\e[0;39m"
brown="\e[1;33m"

packages="$(pkginfo -i | wc -l)"

echo -e "You have $brown$packages$foreground packages installed."
