#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Upload files/scrots to uguu/pomf.se

# TODO: -s and * don't work togheter (as expected), give an error or something

for flag in "$@"; do
	case "$flag" in
		-h|--help)
			echo "-p         permanent/pomf upload"
			echo "-s         upload selection scrot"
			echo "file/url   upload file/url"
			echo "           upload fullscreen scrot"
			exit
			;;
		-p)
			pomf=true
			;;
		-s)
			selection=true
			;;
		*)
			fileurl=true
			fileurllocation="$flag"
			;;
	esac
done

if [[ "$fileurl" == true ]]; then
	if [[ "$flag" =~ ^http ]]; then
		type="$(echo "$fileurllocation" | rev | cut -d "." -f 1 | rev)"
		file="/tmp/file.$type"

		wget --quiet "$fileurllocation" -O "/tmp/file.$type"
	else
		test "$fileurllocation"
		if [[ "$?" -eq 0 ]]; then
			echo "File not found."
			exit
		else
			file="$fileurllocation"
		fi
	fi

	word=file
elif [[ "$selection" == true ]]; then
	file="/tmp/scrot.png"

	maim --hidecursor -s -b 3 -c 250,250,250 "$file" 2> "/dev/null"
	if [[ "$?" -ge 1 ]]; then
		echo "Selection cancelled."
		exit
	fi

	word=selection
else
	file="/tmp/scrot.png"

	maim --hidecursor "$file"
	word=screen
fi

if [[ "$pomf" == true ]]; then
	url="$(curl --silent -F files[]="@$file" "http://pomf.se/upload.php?output=gyazo")"
	notify "Pomfed $word: $url" & disown
else
	url="$(curl --silent -F file="@$file" "http://uguu.se/api.php?d=upload")"
	notify "Uguud $word: $url" & disown
fi

echo "$url" | xclip -selection primary
echo "$url" | xclip -selection clipboard

echo "$url" >> "$HOME/usr/img/pomf.txt"

echo "$url"
