#!/bin/bash
#
# punf - Upload files/scrots to uguu.se/pomf.se
# onodera, https://github.com/onodera-punpun

# TODO: -s and * don't work togheter (as expected), give an error or something
# TODO: make it possible to pipe script into punf

## CONFIGURATION

# Log urls
log=true

# Set log dir location
logdir="$HOME/usr/img"

# Copy links to clipboard (requires xclip)
clipboard=true

# Send notification when upload is done (requires my notify script)
notify=true


## FUNCTIONS




## EXECUTE

for flag in "$@"; do
	case "$flag" in
		-h|--help)
			echo "-p         permanent/pomf upload"
			echo "-s         upload selection scrot"
			echo "file/url   upload file/url"
			echo "           upload fullscreen scrot"
			exit
			;;
		-p)
			pomf=true
			;;
		-s)
			selection=true
			;;
		*)
			fileurl=true
			fileurllocation="$flag"
			;;
	esac
done

# Check if file, url, selection or scrot
if [[ "$fileurl" == true ]]; then
	if [[ "$flag" =~ ^http ]]; then
		type="$(echo "$fileurllocation" | rev | cut -d "." -f 1 | rev)"
		file="/tmp/file.$type"

		wget --quiet "$fileurllocation" -O "/tmp/file.$type"
	else
		test "$fileurllocation"
		if [[ "$?" -ge 1 ]]; then
			echo "File not found."
			exit
		else
			file="$fileurllocation"
		fi
	fi

	# This sets the word used in the echo & notification
	word=file
elif [[ "$selection" == true ]]; then
	file="/tmp/scrot.png"

	maim --hidecursor -s -b 3 -c 250,250,250 "$file" 2> "/dev/null"
	if [[ "$?" -ge 1 ]]; then
		echo "Selection cancelled."
		exit
	fi

	# This sets the word used in the echo & notification	
	word=selection
else
	file="/tmp/scrot.png"

	# Takes screenshot of the whole desktop
	maim --hidecursor "$file"

	# This sets the word used in the echo & notification
	word=screen
fi

# Upload file
if [[ "$pomf" == true ]]; then
	url="$(curl --silent -F files[]="@$file" "http://pomf.se/upload.php?output=gyazo")"

	if [[ "$notify" == true ]]; then
		notify "Pomfed $word: $url" & disown
	fi
else
	url="$(curl --silent -F file="@$file" "http://uguu.se/api.php?d=upload")"
	
	if [[ "$notify" == true ]]; then
		notify "Uguud $word: $url" & disown
	fi
fi

# Copy url to clipboard
if [[ "$clipboard" == true ]];
	echo "$url" | xclip -selection primary
	echo "$url" | xclip -selection clipboard
fi

# Log url
if [[ "$log" == true ]]; then
	echo "$url" >> "$logdir/punf"
fi

echo "$url"
