#!/bin/fish
#
# raingraph - Create graph with raininfo
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Set latitude and longitude
set lat '52.0646'
set lon '5.2065'


## FUNCTIONS

# This function creates the graph
function graph
	gnuplot -e "set terminal png transparent size 211,107;\
				set yrange [0:255];\
				set noborder;\
				set nolabel;\
				set nokey;\
				set notics;\
				set notitle;\
				set style fill solid border rgb '#5394C9';\
				plot '$rainfile' smooth csplines with filledcurve x1 lc rgb '#72A7D3'"
end


## EXECUTE

# Download weather info
set rainfile /tmp/rain.txt
wget -q -O- "http://gps.buienradar.nl/getrr.php?lat=$lat&lon=$lon" | string replace -r '\|.*' '' >$rainfile

if test (count $argv) -ge 1
	graph >$argv
else
	graph >raingraph.png
end
