#!/bin/fish
#
# rmafterd - Removes a file after X minutes/hours/days, daemon part.
# onodera, https://github.com/onodera-punpun

## EXECUTE

while true
	set file (cat $HOME/.rmafter)
	set current (date +"%s")

	for line in $file
		set time (echo $file | cut -d \  -f 1)
		set file (echo $file | cut -d \  -f 2-)

		if test $current -ge $time
			echo "Removing $file."
			rm $file
			echo $line
			sed -i "/$time .*/d" $HOME/.rmafter
		end
	end

	sleep 10m
end
