#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# A script that removes all the scrot in $HOME

count="$(find "$HOME/"*.png 2> "/dev/null" | wc -w)"

if [[ "$count" -eq 1 ]]; then
	rm "$HOME/"*.png
	echo "Removed $count scrot"
elif [[ "$count" -ge 2 ]]; then
	rm "$HOME/"*.png
	echo "Removed $count scrots"
else	
	echo "No scrots to remove"
fi
