#!/bin/fish
#
# scrot - maim wrapper
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Set location where the scrots get saves
set scrotdir $HOME/media/images/scrots


## EXECUTE

if test (count $argv) -ge 1
	switch $argv[1]
		case -h --help
			echo -e 'Usage: scrot [options]\n'
			echo 'options:'
			echo '  -s,   --selection       take selection scrot'
			echo '  -h,   --help            print help and exit'
		case -s --selection
			# Take selection scrot
			maim --hidecursor -s -b 3 -c 250,250,250 $scrotdir/scrot(ls $scrotdir | wc -l).png
			notify 'Scrotted selection' &
		case '*'
			echo 'nvalid option, use -h for help.'
			exit 1
	end
else
	# Take fullscreen scrot
	maim --hidecursor $scrotdir/scrot(ls $scrotdir | wc -l).png
	notify 'Scrotted screen' &
end
