#!/bin/fish
#
# tile - Tile windows
# onodera, https://github.com/onodera-punpun

set location (
	for window in (xdo id -d)
		xwinfo -g $window
	end
)

set 0 0
set 1 0
set 2 0
set 3 0
set 4 0

#  ---------------
# |         |  3  |
# |    1  0 | -2- |
# |         |  4  |
#  ---------------

# Check which slots are not empty
if string match -q -r '1460 895 237 136' $location
	set 0 1
end
if string match -q -r '237 136 942 895' $location
	set 1 1
end
if string match -q -r '1217 136 466 895' $location
	set 2 1
end
if string match -q -r '237 136 945 895' $location
	set 3 1
end
if string match -q -r '237 136 945 895' $location
	set 4 1
end

echo $0$1$2$3$4

if test $0$1$2$3$4 -eq 00000
	xdo resize -w 1460 -h 895
	xdo move -x 237 -y 136
else if test $0$1$2$3$4 -eq 00100 -o 00010 -o 00001 -o 00110 -o 00111 -o 00011
	xdo resize -w 942 -h 895
	xdo move -x 237 -y 136
else if test $0$1$2$3$4 -eq 10000 -o 01000
	xdo move 1217 136 466 895 $window
	xdo move 237 136 942 895 (string match -r '.* 237 136 1460 895' $location | cut -d ' ' -f 1)
end
