#!/bin/fish
#
# updowngraph - Create graph with updown info
# onodera, https://github.com/onodera-punpun

gnuplot -e "set terminal png transparent size 211,135;\
			set yrange [0:100];\
			set noborder;\
			set nolabel;\
			set nokey;\
			set notics;\
			set notitle;\
			set style fill solid border rgb '#BC846F';\
			plot '/tmp/updownd.log' smooth csplines with filledcurve x1 lc rgb '#E5AB96'"
