#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Chooses a random wallpaper from ~/.wallpapers

wallpaperdir="$HOME/.wallpapers"

foreground="\e[0;39m"
brown="\e[1;33m"

wallpaper="$(ls "$wallpaperdir" | shuf -n 1)"

feh --bg-center "$wallpaperdir/$wallpaper" 2> "/dev/null"
echo -e "Wallpaper set, $brown$wallpaper$foreground."
