#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Get da weather

## CONFIGURATION

# Set colors
foreground="\e[0;39m"
brown="\e[1;33m"

## EXECUTE

# Get weather info
info="$(wget -q -O- "http://www.accuweather.com/en/nl/bunnik/250582/weather-forecast/250582" | grep "Bunnik, Netherlands\", daypart:")"
temp="$(echo "$info" | cut -d "'" -f 10- | cut -d "'" -f -1)"
kind="$(echo "$info" | cut -d "'" -f 14- | cut -d "'" -f -1)"

# Echo weather info
echo -e "It's $brown$temp$foreground degrees and the weather type is $brown$kind$foreground."
