#!/bin/bash
#
# punf - Upload files/scrots/urls to sr.ht (rip pomf & uguu)
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Your sr.ht key
key="$(cat "$HOME/.srht")"

# Log urls
log=false

# Set log location
logfile="$HOME/.punf"

# Copy links to clipboard (requires xclip)
clipboard=true

# Send notification when upload is done (requires my notify script)
notify=true

# Open url in browser
browser=false


## FUNCTIONS

# This function sets $file to your clipboard contents
clipboard() {
	uploadme="/tmp/clipboard.txt"

	xclip -o > "$uploadme"

	word=clipboard
}

# This function sets $file to a selection scrot
selection() {
	uploadme="/tmp/scrot.png"

	maim --hidecursor -s -b 3 -c 250,250,250 "$uploadme" 2> "/dev/null"
	if [[ "$?" -ge 1 ]]; then
		echo "Selection cancelled."
		exit 1
	fi

	word=selection
}

# This function sets $file to a url
url() {
	type="$(echo "$@" | rev | cut -d "." -f 1 | rev)"
	uploadme="/tmp/url.$type"

	wget --quiet "$@" -O "$uploadme"

	word=url
}

# This function sets $file to a file
file() {
	if [[ -f "$@" ]]; then
		uploadme="$@"
	else
		echo "File not found."
		exit 1
	fi

	word=file
}

# This function sets $file to a full screen scrot
desktop() {
	uploadme="/tmp/scrot.png"

	maim --hidecursor "$uploadme"

	word=desktop
}

# This function uploads the $file
upload() {
	url="$(curl --silent -F key="$key" -F file="@$uploadme" "https://sr.ht/api/upload" | grep -o -i "https://sr.ht/*.[a-z0-9.]*")"
}

# This function logs the url,  copies the url to the clipboard, and/or opens the url in your browser
feedback() {
	# Copy url to clipboard
	if [[ "$clipboard" == true ]] && [[ "$quiet" == false ]]; then
		echo "$url" | xclip -selection primary
		echo "$url" | xclip -selection clipboard
	fi

	# Log url
	if [[ "$log" == true ]] && [[ "$quiet" == false ]]; then
		echo "$url" >> "$logfile"
	fi

	# Open url in browser
	if [[ "$browser" == true ]] && [[ "$quiet" == false ]]; then
		$BROWSER "$url"
	fi

	# Send notification
	if [[ "$notify" == true ]] && [[ "$quiet" == false ]]; then
		notify "Punfed $word: $url" & disown
	fi
	
	# Send link
	if [[ "$quiet" == true ]]; then
		echo "$url"
	else
		echo "Punfed $word: $url"
	fi
}

## EXECUTE

quiet=false

if [[ "$#" -ge 1 ]]; then
	case "$@" in
		-h|--help)
			echo "usage: punf [options] [file/url]"
			echo "options:"
			echo "  -c,   --clipboard       upload your clipboard as text"
			echo "  -s,   --selection       upload selection scrot"
			echo "  -q,   --quiet           disable all feedback (for scripts using punf)"
			echo "  -v,   --version         print version and exit"
			echo "  -h,   --help            print help and exit"
			exit 0
			;;
		-v|--version)
			echo "punf 0.9.2"
			exit 0
			;;
		-c|--clipboard)
			clipboard
			;;
		-s|--selection)
			selection
			;;
		"-q "*|"--quiet "*)
			quiet=true
			file "$2"
			;;
		http*)
			url "$1"
			;;
		*)
			file "$1"
			;;
	esac
else
	desktop
fi

upload
feedback
