#!/bin/bash
#
# rice - Display some rice info with a smug trianle face
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Resize the terminal
resize=true

# Set colors
foreground="\e[0;39m"
brown="\e[1;33m"

# Set variables
hostname="$(hostname)"
distro="$(crux)"
kernel="$(uname -r -s)"
init="busybox/minirc"
shell=$(echo "$SHELL")
packages="$(pkginfo -i | wc -l)"
wm="wmutils"
font="Gohufont 14"


## EXECUTE

# Resize terminal
if [[ -n "$DISPLAY" ]] && [[ "$resize" == true ]]; then
	#wtp 0 0 200 500 "$(pfw)"
	sleep 0.1
fi

# Echo rice
echo -e "                   $brown$USER$foreground@$brown$hostname$foreground"
echo -e '       /\'
echo -e '      /  \'"         ${brown}Distro:$foreground    $distro"
echo -e '     /    \'"        ${brown}Kernel:$foreground    $kernel"
echo -e '    /˚̆̈̉` ˚̆̈̉` \'"       ${brown}Init/rc:$foreground   $init"
echo -e '   /   レ   \'"      ${brown}Shell:$foreground     $shell"
echo -e '  /     つ   \'"     ${brown}Packages:$foreground  $packages"
echo -e ' /            \'"    ${brown}WM:$foreground        $wm"
echo -e ' ‾‾‾‾‾‾‾‾‾‾‾‾‾‾'"    ${brown}Font:$foreground      $font"
