#!/bin/bash
#
# onodera - onodera at openmailbox dot org
# Chooses a random wallpaper from ~/.wallpapers

## CONFIGURATION

# Set wallpaper dir location
wallpaperdir="$HOME/.wallpapers"

# Set colors
foreground="\e[0;39m"
brown="\e[1;33m"

## EXECUTE

# Get random wallpaper
wallpaper="$(ls "$wallpaperdir" | shuf -n 1)"

# Set random wallpaper
simple-wp-setter  "$wallpaperdir/$wallpaper"
echo -e "Wallpaper set, $brown$wallpaper$foreground."
